// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bnhjqcaxwnltpleefeso.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJuaGpxY2F4d25sdHBsZWVmZXNvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAwNTMxNTIsImV4cCI6MjA2NTYyOTE1Mn0.KG5foaPv9x-AVCTdEDxBLcgP_m7gdcs3oxnV_I8S1JA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);